// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAW8wMGVlwM9J_-iHl4H9BrIn2ecN6kqc',
    appId: '1:941855115112:web:89a44e26d80e19963678dd',
    messagingSenderId: '941855115112',
    projectId: 'en-com-71910',
    authDomain: 'en-com-71910.firebaseapp.com',
    storageBucket: 'en-com-71910.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAhAyphw-TZAhetHOj8Wa4VmrDADu9z5o',
    appId: '1:941855115112:android:82402a60aaaf2c683678dd',
    messagingSenderId: '941855115112',
    projectId: 'en-com-71910',
    storageBucket: 'en-com-71910.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrvTFD2Vvrtn6g3hm435QC6TaNj_n4YMU',
    appId: '1:941855115112:ios:9870ca7e3ba8c4b53678dd',
    messagingSenderId: '941855115112',
    projectId: 'en-com-71910',
    storageBucket: 'en-com-71910.appspot.com',
    androidClientId: '941855115112-ct636lja9b0aha24gqk33skqlg9dnllk.apps.googleusercontent.com',
    iosClientId: '941855115112-enar00on0s5ah3rt5hgo2irh1l30ikm3.apps.googleusercontent.com',
    iosBundleId: 'com.example.enEcommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrvTFD2Vvrtn6g3hm435QC6TaNj_n4YMU',
    appId: '1:941855115112:ios:9870ca7e3ba8c4b53678dd',
    messagingSenderId: '941855115112',
    projectId: 'en-com-71910',
    storageBucket: 'en-com-71910.appspot.com',
    androidClientId: '941855115112-ct636lja9b0aha24gqk33skqlg9dnllk.apps.googleusercontent.com',
    iosClientId: '941855115112-enar00on0s5ah3rt5hgo2irh1l30ikm3.apps.googleusercontent.com',
    iosBundleId: 'com.example.enEcommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAW8wMGVlwM9J_-iHl4H9BrIn2ecN6kqc',
    appId: '1:941855115112:web:d21d6d0980edec373678dd',
    messagingSenderId: '941855115112',
    projectId: 'en-com-71910',
    authDomain: 'en-com-71910.firebaseapp.com',
    storageBucket: 'en-com-71910.appspot.com',
  );

}